services:
  db_dev:
    image: postgres:16
    container_name: yth_db_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yth_dev
    ports:
      - "5432:5432"
    volumes:
      - yth_db_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yth_dev"]
      interval: 3s
      timeout: 3s
      retries: 20

  db_test:
    image: postgres:16
    container_name: yth_db_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yth_test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yth_test"]
      interval: 3s
      timeout: 3s
      retries: 20

volumes:
  yth_db_dev_data:
